default: &default
  adapter: sqlite3
  pool: 5

development:
  <<: *default
  database: db/playheroes_development.sqlite3

test:
  <<: *default
  database: db/playheroes_test.sqlite3

production:
  <<: *default
  database: db/playheroes_production.sqlite3